### ISSUE TITLE
Tip tea-spoon...

### ISSUE THREAD

**Issue by testtip** [testtip/talking-in-public#1]
Thanks for your generosity @block-spider!

**tea-spoon** has not yet linked their wallet with [chaintip](http://www.chaintip.org) to receive tips.

Tip **tea-spoon** by sending Bitcoin Cash (BCH) to:
**bitcoincash:qqh0ld4xhr3r69wd0tpznq5jvnzf27rveu0p9ytdgt**
QR code available on [Bitcoin.com](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4xhr3r69wd0tpznq5jvnzf27rveu0p9ytdgt) | [blockdozer](https://blockdozer.com/insight/address/bitcoincash:qqh0ld4xhr3r69wd0tpznq5jvnzf27rveu0p9ytdgt)

Once you've sent your tip, **tea-spoon** will be asked to link their wallet to collect it.
After linking their wallet, all future tips they receive will be sent to their wallet.

It looks like you've not linked your own wallet to receive tips via [chaintip](http://www.chaintip.org).
You can reply to this message with a BCH receiving address to allow other users to send BCH straight to you. This address will also be used to refund any of the tips you send that are not claimed within one week.

Prefer private communication? Reply with 'private', and **chaintip** will create a private repsitory and send you an invite.

**Comment by block-spider** [comment]
private

**Comment by block-spider** [comment]
private
