### ISSUE TITLE
Tip tea-spoon...

### ISSUE THREAD

**Issue by testtip** [testtip/talking-in-public#2]
@block-spider, **tea-spoon** has not yet linked their wallet with [chaintip](http://www.chaintip.org) to receive tips.

Tip **tea-spoon** by sending Bitcoin Cash (BCH) to:
**bitcoincash:qqh0ld4dmuusukhk5382h5guganfncjkvsmte9lhgc**
QR code available on [Bitcoin.com](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4dmuusukhk5382h5guganfncjkvsmte9lhgc) | [blockdozer](https://blockdozer.com/insight/address/bitcoincash:qqh0ld4dmuusukhk5382h5guganfncjkvsmte9lhgc)

Once you've sent your tip, **tea-spoon** will be asked to link their wallet to collect it.
After linking their wallet, all future tips they receive will be sent to their wallet.

It looks like you've not linked your own wallet to receive tips via [chaintip](http://www.chaintip.org). You can reply to this message with a BCH receiving address to allow other users to send BCH straight to you. This address will also be used to refund any of the tips you send that are not claimed within one week.

Prefer private communication? Reply with 'private', and **chaintip** will invite you to a private repsitory.

**Comment by testtip** [comment]
hello

**Comment by block-spider** [comment]
hello

**Comment by block-spider** [comment]
hello

**Comment by block-spider** [comment]
oh noes

**Comment by block-spider** [comment]
lsdkjfsdljfj

**Comment by block-spider** [comment]
hello

**Comment by testtip** [comment]
Unfortunately, this [chaintip](http://www.chaintip.org) bot is unable to understand your message.

Please respond with a Bitcoin Cash receiving address so that users can send tips straight to your wallet. If you don't have a Bitcoin Cash wallet, you can get one free from [Bitcoin.com](https://www.bitcoin.com/choose-your-wallet/bitcoin-com-wallet) 

Click "Receive" on your wallet to obtain your receiving address. Then paste it as a reply to this message.

If you'd like to talk to a human, please click [here](https://www.reddit.com/message/compose/?to=Tibanne).

**Comment by testtip** [comment]
private

**Comment by block-spider** [comment]
private

**Comment by block-spider** [comment]
private
